computacao/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'computacao'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('index/', views.index, name='index'),
                  path('afd0/', views.afd0, name='afd0'),
                  path('automatos/', views.automatos, name='automatos'),
                  path('novo_automato/', views.novo_automato, name='novo_automato'),
                  path('edita_automato/<int:automato_id>/', views.edita_automato, name='edita_automato'),
                  path('apaga_automato/<int:automato_id>/', views.apaga_automato, name='apaga_automato'),
                  path('<int:automato_id>/automato/', views.automato, name='automato')
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('computacao.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

computacao/models.py
# Create your models here.
from django.db import models
from graphviz import Digraph
import os
from django.conf import settings


class Automato(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=100)
    alfabeto = models.CharField(max_length=100)
    estados = models.CharField(max_length=100)
    estadoInicial = models.CharField(max_length=100)
    estadosDeAceitacao = models.CharField(max_length=100)
    dicionarioTransicao = models.CharField(max_length=1000)
    diagrama = models.FileField(upload_to='afd_diagrams/', blank=True, null=True)

    def __str__(self):
        return self.descricao

    def printAlfabeto(self):
        return str(set(self.alfabeto.split()))

    def printEstados(self):
        return str(set(self.estados.split()))

    def printEstadosDeAceitacao(self):
        return str(set(self.estadosDeAceitacao.split()))

    def dTransInTable(self):
        dTrans = {(t.split('-')[0], t.split('-')[1]):t.split('-')[2] for t in self.dicionarioTransicao.split()}

        table = []

        linha = ['']
        for simbolo in self.alfabeto.split():
            linha.append(simbolo)
        table.append(linha)

        for estado in self.estados.split():
            linha =[estado]
            for simbolo in self.alfabeto.split():
                linha.append(dTrans[(estado, simbolo)])
            table.append(linha)

        return table

    def valida_sequencia(self, sequencia):

        estado = self.estadoInicial

        dTrans = {(t.split('-')[0], t.split('-')[1]):t.split('-')[2] for t in self.dicionarioTransicao.split()}

        for simbolo in sequencia:
            if simbolo in self.alfabeto:
                estado = dTrans[(estado, simbolo)]
            else:
                return False

        if estado in self.estadosDeAceitacao:
            return True
        else:
            return False


    def desenha_diagrama(self):

        d = Digraph(name=self.descricao)

        # configurações gerais
        d.graph_attr['rankdir'] = 'LR'
        d.edge_attr.update(arrowhead='vee', arrowsize='1')
        # d.edge_attr['color'] = 'blue'
        d.node_attr['shape'] = 'circle'
        # d.node_attr['color'] = 'blue'

        # Estado inicial
        d.node('Start', label='', shape='none')

        # Estados de transição
        estadosDeTransicao = set(self.estados.split()) - set(self.estadosDeAceitacao.split())
        for estado in estadosDeTransicao:
            d.node(estado)

        # Estado aceitação
        for estado in self.estadosDeAceitacao.split():
            d.node(estado, shape='doublecircle')

        # Transicoes
        d.edge('Start', self.estadoInicial)

        for transicao_comma in self.dicionarioTransicao.split():
            transicao = transicao_comma.split('-')
            d.edge(transicao[0], transicao[2], label=transicao[1])

        d.format = 'svg'
        # self.diagrama = f"project/computacao/images/afd/{str(self.nome).replace(' ', '_')}.svg"
        # d.render(f"project/computacao/static/computacao/images/afd/{str(self.nome).replace(' ', '_')}")

        file_name = f"{str(self.nome).replace(' ', '_')}.svg"
        file_path = os.path.join(settings.MEDIA_ROOT, 'afd_diagrams', file_name)
        # d.render(file_path)
        svg_data = d.pipe(format='svg')

        # Write the SVG data to the file
        with open(file_path, 'wb') as f:
            f.write(svg_data)

        self.diagrama.name = f"afd_diagrams/{file_name}"
        self.save()

class ValidaSequencia():
    descricao = 'AFD que aceita sequências binárias terminadas em 0'
    alfabeto = '01'
    estados = ['A', 'B']
    estadoInicial = 'A'
    estadosDeAceitacao = {'B'}
    dicionarioTransicao = {
        ('A', '0'): 'B',
        ('A', '1'): 'A',
        ('B', '0'): 'B',
        ('B', '1'): 'A'
    }

    def validar(self, sequencia):
        # Autómato em funcionamento
        estado = self.estadoInicial

        for simbolo in sequencia:
            if simbolo in self.alfabeto:
                estado = self.dicionarioTransicao[(estado, simbolo)]
            else:
                break

        if estado in self.estadosDeAceitacao:
            return True
        else:
            return False

computacao/forms.py
from django import forms
from django.forms import ModelForm
from .models import Automato


class SequenciaForm(forms.Form):
    sequencia = forms.CharField(label='',
                                widget=forms.TextInput(attrs={
                                    'placeholder': 'insira uma sequência binária',
                                    'size': '25'
                                }))


class AutomatoForm(ModelForm):
    class Meta:
        model = Automato
        fields = '__all__'   # pode-se especificar lista dos campos q queremos. podemos querer tudo excluindo alguns
        exclude = ['diagrama']

        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'AFD que aceita sequências ...'}),
            'alfabeto': forms.TextInput(attrs={'class': 'form-control'}),
            'estados': forms.TextInput(attrs={'class': 'form-control'}),
            'estadoInicial': forms.TextInput(attrs={'class': 'form-control'}),
            'estadosDeAceitacao': forms.TextInput(attrs={'class': 'form-control'}),
            'dicionarioTransicao': forms.TextInput(attrs={'class': 'form-control'}),
        }

        labels = {
            'nome': 'Nome do autómato',
            'descricao': 'Descrição',
            'alfabeto': 'Alfabeto de símbolos',
            'estados': 'Estados',
            'estadoInicial': 'Estado inicial',
            'estadosDeAceitacao': 'Estado de aceitação',
            'dicionarioTransicao': 'Transições'
        }

        placeholders = {
            'nome': 'Nome do autómato',
            'descricao': 'Descrição',
            'alfabeto': 'Alfabeto de símbolos',
            'estados': 'Estados',
            'estadoInicial': 'Estado inicial',
            'estadosDeAceitacao': 'Estado de aceitação',
            'dicionarioTransicao': 'Transições'
        }

        help_texts = {
            'nome': 'Atribua um nome, com no máximo 3 palavras,  que identifique o AFD',
            'descricao': 'Descreva o tipo de sequências que o autómato reconhece',
            'alfabeto': 'Insira os simbolos do alfabeto separados por espaços (e.g. "0 1")',
            'estados': 'Insira os nomes dos estados separados por espaços (e.g. "A B")',
            'estadosDeAceitacao': 'Insira os estados separados por espaços (e.g. "A B")',
            'dicionarioTransicao': 'Insira as transicoes estadoInicial-simbolo-estadoSeguinte (e.g. "A-0-B A-1-A")'
        }

computacao/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Automato, ValidaSequencia
from .forms import SequenciaForm, AutomatoForm


def index(request):
    return render(request, 'computacao/index.html')


def afd0(request):

    a = ValidaSequencia()
    resultado = None
    sequencia = None

    if request.method == 'POST':
        form = SequenciaForm(request.POST)
        if form.is_valid():
            sequencia = form.cleaned_data['sequencia']
            resultado = a.validar(sequencia)

    context = {
        'form': SequenciaForm(),
        'resultado': resultado,
        'sequencia': sequencia,
        'descricao': a.descricao
    }
    return render(request, 'computacao/afd0.html', context)


def automato(request, automato_id):

    sequencia = None
    resultado = None

    form = SequenciaForm(request.POST or None)
    if form.is_valid():
        sequencia = form.cleaned_data['sequencia']
        resultado = Automato.objects.get(id=automato_id).valida_sequencia(sequencia)

    context = {
        'automato': Automato.objects.get(id=automato_id),
        'sequencia': sequencia,
        'resultado': resultado,
        'form': form,
    }
    return render(request, 'computacao/automato.html', context)
    # """return render(request, 'computacao/test.html', {'automato_id':automato_id})"""

def automatos(request):

    context = {'automatos': Automato.objects.all()}
    return render(request, 'computacao/automatos.html', context)


def novo_automato(request):

    form = AutomatoForm(request.POST or None)
    if form.is_valid():
        new_automata = form.save()
        new_automata.desenha_diagrama()
        new_automata.save()
        return HttpResponseRedirect(reverse('computacao:automatos'))

    context = {'form': form}

    return render(request, 'computacao/novo_automato.html', context)


def edita_automato(request, automato_id):
    """if request.POST == 'POST':
        form = AutomatoForm(request.POST)
        form.save()"""

    instance = Automato.objects.get(id=automato_id)
    form = AutomatoForm(request.POST or None, instance=instance)
    if form.is_valid():
        a = form.save()
        a.desenha_diagrama()
        a.save()
        return HttpResponseRedirect(reverse('computacao:automatos'))

    """
    form = AutomatoForm(initial={
        'nome': automato_a_editar.nome,
        'descricao': automato_a_editar.descricao,
        'alfabeto': automato_a_editar.alfabeto,
        'estados': automato_a_editar.estados,
        'estadoInicial': automato_a_editar.estadoInicial,
        'estadosDeAceitacao': automato_a_editar.estadosDeAceitacao,
        'dicionarioTransicao': automato_a_editar.dicionarioTransicao,
    })"""
    context = {'form': form, 'automato_id':automato_id}
    return render(request, 'computacao/edita_automato.html', context)

def apaga_automato(request, automato_id):
    Automato.objects.filter(id=automato_id).delete()
    context = {'automatos': Automato.objects.all()}
    return render(request, 'computacao/automatos.html', context)

computacao/templates/computacao/afd0.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
        <h3>Autómato Finito Determinístico</h3>
        <p>{{ descricao }}. Valide uma sequência, verificando se faz parte da linguagem que esta reconhece: </p>
        <form action="{% url 'computacao:afd0' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="validar">
        </form>

        {% if resultado != None %}
           {% if resultado == True %}
               <br><p>A sequência <code>{{ sequencia }}</code> é aceite pelo autómato </p>
           {% else %}
               <br><p>A sequência <code>{{ sequencia }}</code> não é aceite pelo autómato </p>
           {% endif %}
        {% else %}
            <br><br>
        {% endif %}
    </main>
{% endblock %}

computacao/templates/computacao/automato.html
{% extends 'computacao/layout.html' %}

{% block main %}


    <main class="col-sm-12">

        <h3>{{ automato.nome|title }}</h3>

        <p>{{ automato.descricao }}.</p>

        <table align="center">
            <tr align="left">
                <td>
                    <p> <b>Quíntuplo do autómato</b></p>
                    <ul>
                    <li>Alfabeto: {{ automato.printAlfabeto }} </li>
                    <li>Estados: {{ automato.printEstados }}</li>
                    <li>Estado inicial: {{ automato.estadoInicial }}</li>
                    <li>Estados aceitação: {{ automato.printEstadosDeAceitacao }}</li>

                    <li>Tabela de transições:
                    <table align="center" rules="all" style="border-collapse: collapse; padding:5px;">
                        {% for dTran in automato.dTransInTable %}
                            <tr>
                                {% for element in dTran %}
                                    {% if forloop.parentloop.first %}
                                        <th style="padding:5px;">{{ element }}</th>
                                    {% elif forloop.first %}
                                        <th style="padding:5px;">{{ element }}</th>
                                    {% else %}
                                        <td style="padding:5px;">{{ element }}</td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    </ul>
                </li>
                </td>
                <td>
                    <p style="text-align: right; margin-top: -15px;"><b>Diagrama de transições</b></p>
                    {% load static %}
                    <img src="{{ automato.diagrama.url }}" alt="">

                </td>
            </tr>
        </table>


        <br>
        <p><b>Validador:</b> Insira uma sequência e verifique se pertence à linguagem que o AFD reconhece: </p>
        <form action="{% url 'computacao:automato' automato.id %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="validar" class="btn btn-success">
        </form>

        {% if resultado != None %}
            {% if resultado == True %}
                <p>A sequência <b>{{ sequencia }}</b> é aceite pelo autómato </p>
            {% else %}
                <p>A sequência <b>{{ sequencia }}</b> não é aceite pelo autómato </p>
            {% endif %}
        {% else %}
            <br><br>
        {% endif %}


    </main>

{% endblock %}


{% block aside %}
{% endblock %}

computacao/templates/computacao/automatos.html
{% extends 'computacao/layout.html' %}

{% block main %}

    <main class="col-sm-12 text-center">

        <h3>Autómatos Finitos Determinísticos (AFD)</h3>

        <p>Apresentam-se em baixo autómatos que foram criados.</p>
        <br><br>
        <table align="center" class="table" style="max-width:900px">
            <tr>
                <th class="text-center">Diagrama de Estados</th>
                <th class="text-center">Descrição</th>
            </tr>
            {% load static %}
            {% for automato in automatos %}
                <tr class="text-left">
                    <td>
                        <a href="{% url 'computacao:automato' automato.id %}">
                            <img src="{{ automato.diagrama.url }}" alt="" width="80%">
                        </a>
                    </td>
                    <td style="vertical-align:bottom">
                        <p>{{ automato.descricao }}</p>
                        <p>
                            <a href="{% url 'computacao:automato' automato.id %}" class="btn btn-info  btn-sm">
                                Detalhes
                            </a>
                            <a href="{% url 'computacao:automato' automato.id %}" class="btn btn-success  btn-sm">
                                Validar Sequência
                            </a>
                            <a href="{% url 'computacao:edita_automato' automato.id %}" class="btn btn-warning  btn-sm">
                                Editar AFD
                            </a>
                            <a href="{% url 'computacao:apaga_automato' automato.id %}" class="btn btn-danger  btn-sm">
                                Apagar AFD
                            </a>
                        </p>

                    </td>

                </tr>
            {% endfor %}
        </table>

        <a href="{% url 'computacao:novo_automato' %}" class="btn btn-success btn-sm btn-block">
            Crie um novo AFD
        </a>

    </main>

{% endblock %}

{% block aside %}
{% endblock %}

computacao/templates/computacao/edita_automato.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-12">
        <h3>Autómato Finito Determinístico</h3>
        <p>Pode aqui especificar um novo autómato que ficará armazenado na base de dados, juntamente com o seu diagrama.
            O autómato será implementado e poderá ser usado.</p>

        <form class="form-group" action="{% url 'computacao:edita_automato' automato_id %}" method="POST">

            {% csrf_token %}

            {{ form.as_p }}

            <div class="text-right">
                <a href="{% url 'computacao:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>

        </form>

    </main>
{% endblock %}

computacao/templates/computacao/index.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
        <blockquote class="blockquote">
            <p class="mb-0">Os limites da minha linguagem são os limites do meu mundo.</p>
            <footer class="blockquote-footer">Ludwig Wittgnestein</footer>
        </blockquote>
        <p>A teoria da computação é um subcampo da ciência da computação e matemática que busca determinar quais
            problemas podem ser computados em um dado modelo de computação. A computação pode ser definida como a
            solução de um problema ou, formalmente, o cálculo de uma função por meio de um algoritmo. Apesar de
            intuitivo na história humana, o conceito de execução de uma tarefa com passos finitos a fim de se obter um
            resultado, ou seja, um algoritmo, não possuía uma definição formal até a conceituação do modelo de Máquina
            Universal de Turing.</p>
        <!--
                <p>Qualquer linguagem é necessáriamente um sistema finito aplicado, com diferentes graus de criatividade a uma
                    variedade infinita de situações. David Lodge</p>
                <p>A linguagem é uma forma da razão humana, que tem sua lógica interna da qual o homem nada sabe. Claude
                    Levi-Strauss</p>
                <p>As máquinas são adoradas porque são bonitas e valorizadas porque conferem poder; são odiadas porque são
                    hediondas e porque impõem a escravidão. Bertrand Russel.</p>
                <p>A teoria pode deixar perguntas sem resposta, mas a prática tem que inventar algo. Mason Cooley</p>
        -->
    </main>

    <aside class="col-sm-6 text-center">
        <br><br><br>
        {% load static %}
        <img src="{% static 'computacao/images/turing-machine.png' %}" alt="">
        <blockquote class="blockquote">
            <p class="mb-0">Uma máquina pode fazer o trabalho de cinquenta homens comuns. Nenhuma máquina pode fazer o
                trabalho de um
                homem extraordinário.</p>
            <footer class="blockquote-footer">Elbert Hubbard</footer>
        </blockquote>
    </aside>

{% endblock %}

computacao/templates/computacao/layout.html
<!DOCTYPE html>
<html lang="en">
<head>

   <!--
    templates:
        https://www.w3schools.com/bootstrap/bootstrap_templates.asp
      https://www.w3schools.com/bootstrap/
      https://www.w3schools.com/w3css/w3css_templates.asp

      how to create a Web Page: https://www.w3schools.com/w3css/w3css_web_tmp_band.asp
   -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teoría da Computação</title>

    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'computacao/images/favicon.png' %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'computacao/style.css' %}">

</head>
<body>
    <header class="jumbotron text-center">
        <h1>Teoría da Computação</h1>
        <nav>
            <a href="{% url 'computacao:index' %}" class="btn btn-info" role="button">Introdução</a>
            <a href="{% url 'computacao:automatos' %}" class="btn btn-info" role="button">Autómatos</a>
            <a href="" class="btn btn-info" role="button">Máquinas de Turing</a>
        </nav>
    </header>
    <div  class="text-center">
         {% block main %}
        {% endblock %}
    </div>

</body>
</html>

computacao/templates/computacao/novo_automato.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
        <h3>Autómato Finito Determinístico</h3>
        <p>Pode aqui especificar um novo autómato que ficará armazenado na base de dados, juntamente com o seu diagrama.
            O autómato será implementado e poderá ser usado.</p>

        <form class="form-group" action="{% url 'computacao:novo_automato' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-right">
                <a href="{% url 'computacao:automatos' %}" role="button" class="btn btn-warning">Cancelar</a>
                <input type="submit" class="btn btn-success" value="submeter">
            </div>
        </form>
    </main>
    <aside class="col-sm-6 text-center">
        <br><br><br>
        {% load static %}

        <blockquote class="blockquote">
            <p class="mb-0"><img src="{% static 'computacao/images/turing-machine.png' %}" alt="">
                <br>
                Uma máquina pode fazer o trabalho de cinquenta homens comuns. Nenhuma máquina pode fazer o
                trabalho de um
                homem extraordinário.</p>
            <footer class="blockquote-footer">Elbert Hubbard</footer>
        </blockquote>
    </aside>
{% endblock %}

computacao/templates/computacao/test.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-6">
       {{ automato_id }}
    </main>
{% endblock %}

computacao/templates/computacao/validador.html
{% extends 'computacao/layout.html' %}

{% block main %}
    <main class="col-sm-12">
        <h3>Autómato Finito Determinístico</h3>
        <p>{{ descricao }}. Valide uma sequência, verificando se faz parte da linguagem que esta reconhece: </p>
        <form action="{% url 'computacao:afd0' %}" method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="validar">
        </form>

        {% if resultado != None %}
           {% if resultado == True %}
               <br><p>A sequência <code>{{ sequencia }}</code> é aceite pelo autómato </p>
           {% else %}
               <br><p>A sequência <code>{{ sequencia }}</code> não é aceite pelo autómato </p>
           {% endif %}
        {% else %}
            <br><br>
        {% endif %}
    </main>
{% endblock %}